### ISSUE TITLE
高機能版API/structの追加

### ISSUE THREAD

**Issue by k-matsuzawa** [cryptogarageinc/cfd-go#154]
# Overview

- cfd-goは初期の実装を追従してきたが、他のC-API系がオブジェクト構造化しているため、cfd-goも構造化/高機能化を行う。
  - 基本的にはC#をベースに、一部C++を取り入れる。
- なおcfd-js（JSON-API系）はJSON投入前提のため、オブジェクト指向での実装はしていない。

# Completion condition

- 新規でstruct構造を作成する。

**Comment by ko-matsu** [comment]
closeすること。
